# Generated by Django 5.0.4 on 2024-04-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0003_remove_product_category_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
